version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - Coherence_API_KEY=NWEbBvAgeTkoBavIXzZYlyaNjvJJmjWrFnIm82Bw
